### ISSUE TITLE
Font generating

### ISSUE THREAD

**Issue by jon4hz** [semimqmo/sekiro_grub_theme#5]
Hi!

May I ask how you generated the `.pf2` fonts for that theme? 

I'm trying to modify it to a Malenia (Elden Ring) theme but changing the font breaks things for me. (see https://i.imgur.com/Smf2u3Z.jpg)

I generated the fonts using `grub-mkfont -s 16 -o mantinia_16.pf2  Mantinia-Regular.ttf`

**Comment by semimqmo** [comment]
Hi, 
I created the font the same way you did.
I don't really get what the issue with your font is.
If your problem is that it's cut off and not scaled properly, then I think that's only because the window is the wrong resolution.
Just as a tip: you don't have to use VMs to test it; [this](https://github.com/hartwork/grub2-theme-preview) worked really well.

Looks cool btw! :)

**Comment by jon4hz** [comment]
Hey, thanks! Most of the hard work was done by you so thanks for that, haha.

Actually I'm already using grub2-theme-preview to test this. I specified the screen size using the correct parameter. When I tested it with the original font from your sekiro theme, it scaled properly. However, when I changed the font it broke the scaling (both qemu windows in the screenshot were started with the exact same command, just a different front). 
In the meantime I installed this on my machine and it seems to work but that could be just a coincidence since the wallpaper matches my screen size. 
I suspect that it might be an issue with either grub2-theme-preview or the font itself but I have no idea how to fix it. 
Anyway... thanks a lot for your answer!
